name: DeployToGitHubPages
env:
  PUBLISH_DIR: SharpRISCV/WebRISCV/bin/Release/net7.0/publish/

# Controls when the action will run
on:
  workflow_dispatch:

jobs:
  build:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2

    # publishes Blazor project to the release-folder
    - name: Publish app
      run: dotnet publish ./WebRISCV/WebRISCV.csproj -c Release
        
    # changes the base-tag in index.html from '/' to 'SharpRISCV' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to SharpRISCV
      run: sed -i 's/<base href="\/" \/>/<base href="\/SharpRISCV\/" \/>/g' SharpRISCV/WebRISCV/bin/Release/net7.0/wwwroot
    
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
